server_port="5533"
server_addr="127.0.0.1:5533" # replce it to server "IP"
server_addr="remote-server:5533" # replce it to remote server
dns_server="114.114.114.114"
# client_ip="192.168.0.1"
blocklist=[
    "*.*.google.com", # google
    "g.co",
    "*.*.goo.gl",
    "*.googleusercontent.com",
    "*.googleapis.com",
    "gmail.com",
    "*.youtube.com", # youtube
    "*.ytimg.com",
    "*.ggpht.com",
    "*.googlevideo.com",
    "*.vimeo.com",
    "*.facebook.com", # facebook
    "*.xx.fbcdn.net",
    "connect.facebook.net",
    "*.twitter.com", # twitter
    "t.co",
    "*.twimg.com",
    "www.linkedin.com",
    "www.reddit.com", # reddit
    "www.redditmedia.com",
    "*.*.blogspot.com", # blogspot
    "www.blogger.com",
    "www.feedburner.com",
    "img1.blogblog.com",
    "*.*.aws.amazon.com", # amazon
    "m.media-amazon.com",
    "*.awsstatic.com",
	"*.*.*.cloudfront.net", # atlassian
    "*.medium.com",
    "accounts-static.cdn.mozilla.net", # firefox
    "pocket-image-cache.com", # pocket
    "*.golang.org", # golang
    "go.googlesource.com",
    "gist.github.com", # github
    "*.k8s.io", # k8s
    "k8s.gcr.io",
    "*.wikipedia.org", # wikipeida
    "*.wikimedia.org",
    "*.wikisource.org",
    "lookup-api.apple.com",
    "lookup-api.apple.com.edgekey.net",
    "e16991.b.akamaiedge.net",
    "*.web.telegram.org", # telegram
    "core.telegram.org",
    "telegram.me",
    "t.me",
    "*.slack.com", #slack
    "*.slack-edge.com",
    "js.driftt.com",
    "cloud.feedly.com", # feedly
    "static.grammarly.com", # grammarly
    "apkpure.com", # apkpure
    "download.apkpure.com",
    "*.nytimes.com", # New York times
    "*.nyt.com",
    "bandwagonhost.com", # bandwagonhost
    "www.bwh1.net",
]
verbose=1
