server_port="5533"
server_addr="127.0.0.1:5533" # replce it to server "IP"
server_addr="remote-server:5533" # replce it to remote server
dns_server="114.114.114.114"
# client_ip="192.168.0.1"
blocklist=[
    "*.*.google.com", # google
    "*.googleusercontent.com",
    "gmail.com",
    "*.youtube.com", # youtube
    "*.ytimg.com",
    "*.ggpht.com",
    "*.googlevideo.com",
    "*.vimeo.com",
    "*.facebook.com", # facebook
    "*.xx.fbcdn.net",
    "*.twitter.com", # twitter
    "*.twimg.com",
    "www.reddit.com", # reddit
    "www.redditmedia.com",
    "*.*.blogspot.com", # blogspot
    "www.blogger.com",
    "www.feedburner.com",
    "img1.blogblog.com",
    "*.*.aws.amazon.com", # amazon
    "m.media-amazon.com",
    "*.awsstatic.com",
    "*.atlassian.net", # atlassian
    "*.atlassian.com",
    "*.prod.public.atl-paas.net",
	"*.cloudfront.net",
    "*.golang.org", # golang
    "go.googlesource.com",
	"gist.github.com",
    "*.k8s.io",
    "*.wikipedia.org", # wikipeida
    "*.wikimedia.org",
    "*.wikisource.org",
    "lookup-api.apple.com",
    "lookup-api.apple.com.edgekey.net",
    "e16991.b.akamaiedge.net",
    "*.web.telegram.org", # telegram
    "t.me",
    "*.slack.com", #slack
    "*.slack-edge.com",
    "js.driftt.com",
    "cloud.feedly.com", # feedly
    "*.nytimes.com", # New York times
    "*.nyt.com",
]
verbose=0
