server_port="5533"
server_addr="127.0.0.1:5533" # replce it to server "IP"
dns_server="114.114.114.114"
# client_ip="192.168.0.1"
blocklist=[
    "*.google.com", # google
    "*.googleusercontent.com",
    "*.youtube.com", # youtube
    "*.ytimg.com",
    "*.ggpht.com",
    "*.googlevideo.com",
    "*.vimeo.com",
    "*.facebook.com", # facebook
	"*.xx.fbcdn.net",
    "*.twitter.com", # twitter
	"*.twimg.com",
    "*.*.blogspot.com", # blogspot
    "www.blogger.com",
    "www.feedburner.com",
    "img1.blogblog.com",
    "*.golang.org", # golang
    "go.googlesource.com",
    "*.wikipedia.org", # wikipeida
	"*.wikimedia.org",
	"*.wikisource.org",
	"lookup-api.apple.com",
	"lookup-api.apple.com.edgekey.net",
	"e16991.b.akamaiedge.net",
    "*.web.telegram.org", # telegram
	"cloud.feedly.com", # feedly
    "*.nytimes.com", # New York times
    "*.nyt.com",
]
verbose=0